#数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java21?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
#    type: org.apache.commons.dbcp2.BasicDataSource　



#mybatis:  扫描xml文件
#  config-location: classpath:/mybatis-config.xml #加载配置文件
#  config-locations: classpath:/mapper/**  #加载映射文件


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


